[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools >= 64", "setuptools-scm>=8"]

[tool.setuptools_scm]
git_describe_command = "git describe --long --first-parent"
root = "../../.."

[project]
name = "aiqtoolkit-test"
dynamic = ["version"]
dependencies = ["nvidia-nat[test]~=1.3"]
readme = "pypi.md"
description = "Transitional package for nvidia-nat-test, this package is deprecated and will be removed in the future."
classifiers = ["Programming Language :: Python"]
